-- Initialize the database.
-- Drop any existing data and create empty tables.

DROP TABLE IF EXISTS ELEMENT_ID;
DROP TABLE IF EXISTS VEVENTSCREEN;


CREATE TABLE ELEMENT_ID (
  --id INTEGER PRIMARY KEY AUTOINCREMENT,
  ElEMENT_ID INTEGER UNIQUE NOT NULL,
  ELEMENT_NAME TEXT NOT NULL,
);

CREATE TABLE VEVENTSCREEN (
  --id INTEGER PRIMARY KEY AUTOINCREMENT,
  ElEMENT_ID INTEGER NOT NULL,
  TS TIMESTAMP(9) NOT NULL,
  VALUE_NUMBER BINARY_DOUBLE, NOT NULL,
);
